version: '3'

services:
  web:
    build: ./app
    image: master-image
    ports:
      - 5000:5000
    command: /usr/local/bin/gunicorn -b :5000 main:app

# uncomment to have a another worker
#  worker2:
#    image: master-image
#    depends_on:
#      - redis
#    command: rqworker --name worker2 --url redis://redis:6379/0
# Reference: https://github.com/volkerp/flaskrqdemo/blob/master/docker-compose.yml